#!/usr/bin/env bash

red() { printf '\033[31m%s\033[0m' "$1"; }
blue() { printf '\033[34m%s\033[0m' "$1"; }
green() { printf '\033[92m%s\033[0m' "$1"; }
yellow() { printf '\033[93m%s\033[0m' "$1"; }
newline() { printf '\n'; }

function getvar {
    local jokes=(
        "Maybe your passwords need a little couples therapy."
        "Even Darth Vader had better password hygiene than this."
        "Caps lock got you again? Maybe try lowercase this time."
        "Looks like your passwords are having an identity crisis."
        "Don't match, maybe they're looking for some extra spark?"
        "This might be the sign you need to upgrade your password game!"
        "My apologies, even your pet goldfish could guess this password!"
        "Looks like your love life isn't the only thing with match issues."
        "Your passwords are like a bad dream, wish they would just disappear."
        "Don't worry, I'm sure even a trained monkey could crack those passwords eventually."
    )
    while true; do
        read -p "Enter $(red "hostname"): " hostname
        [ -z "$hostname" ] && continue
        break
    done
}
getvar
